### ISSUE TITLE
Exception while triggering export with "Trigger Realtime Export"

### ISSUE THREAD

**Issue by kasialukoszek** [Flagbit/Magento-FACTFinder#158]
Current Version 4.1.3 
PHP Version: 5.5.35
Customization: no customization which effects FACT-Finder. 
Magento ver. 1.14.2.4

When clicking on System/Configuration/Catalog/FACT-Finder Export Configuration/FACT-Finder/Trigger Realtime Export ww've got an exception:

We were asked by Mr Tansel Kacamak from FACT-Finder to use the 4.1.3 because it is the most stable version. 

```

exception 'Exception' with message 'Warning: strip_tags() expects parameter 1 to be string, array given  in /var/www/html/fact-finder/web/app/code/community/FACTFinder/Core/Model/Export/Product.php on line 954' in /var/www/html/fact-finder/web/app/code/core/Mage/Core/functions.php:245
Stack trace:
#0 [internal function]: mageCoreErrorHandler(2, 'strip_tags() ex...', '/var/www/html/f...', 954, Array)
#1 /var/www/html/fact-finder/web/app/code/community/FACTFinder/Core/Model/Export/Product.php(954): strip_tags(Array)
#2 /var/www/html/fact-finder/web/app/code/community/FACTFinder/Core/Model/Export/Product.php(735): FACTFinder_Core_Model_Export_Product->_removeTags(Array, '2')
#3 /var/www/html/fact-finder/web/app/code/community/FACTFinder/Core/Model/Export/Product.php(382): FACTFinder_Core_Model_Export_Product->_getAttributesRowArray(Array, Array, '2')
#4 /var/www/html/fact-finder/web/app/code/community/FACTFinder/Core/Model/Export/Product.php(232): FACTFinder_Core_Model_Export_Product->doExport('2')
#5 /var/www/html/fact-finder/web/app/code/community/FACTFinder/Core/controllers/ExportController.php(85): FACTFinder_Core_Model_Export_Product->saveExport('2')
#6 /var/www/html/fact-finder/web/app/code/core/Mage/Core/Controller/Varien/Action.php(418): FACTFinder_Core_ExportController->exportAction()
#7 /var/www/html/fact-finder/web/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('export')
#8 /var/www/html/fact-finder/web/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#9 /var/www/html/fact-finder/web/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#10 /var/www/html/fact-finder/web/app/Mage.php(692): Mage_Core_Model_App->run(Array)
#11 /var/www/html/fact-finder/web/index.php(83): Mage::run('', 'store')
#12 {main}

#0 /var/www/html/fact-finder/web/app/code/community/FACTFinder/Core/Model/Export/Product.php(234): Mage::throwException(Object(Exception))
#1 /var/www/html/fact-finder/web/app/code/community/FACTFinder/Core/controllers/ExportController.php(85): FACTFinder_Core_Model_Export_Product->saveExport('2')
#2 /var/www/html/fact-finder/web/app/code/core/Mage/Core/Controller/Varien/Action.php(418): FACTFinder_Core_ExportController->exportAction()
#3 /var/www/html/fact-finder/web/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('export')
#4 /var/www/html/fact-finder/web/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#5 /var/www/html/fact-finder/web/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#6 /var/www/html/fact-finder/web/app/Mage.php(692): Mage_Core_Model_App->run(Array)
#7 /var/www/html/fact-finder/web/index.php(83): Mage::run('', 'store')
#8 {main}

```

**Comment by tuegeb** [comment]
Thanks for this bug report. The issue has already been solved: https://github.com/Flagbit/Magento-FACTFinder/releases/tag/v4.1.4
