### ISSUE TITLE
two errors swamp the logs FF3.5.4

### ISSUE THREAD

**Issue by Sidt** [Flagbit/Magento-FACTFinder#85]
Hi there,

we have installed the factfinder extension version  3.5.4. We know that this is not the current one, but we couldn't update it at this moment. The Extension is used in two of our systems and we need many quality tests to ensure that the update is working fine with our own extensions and this is at our current step of development to critical. So I hope you can tell us the fix. Here are the two errors which swamp our exception logs of Magento:

**Number one**
```
2014-12-14T05:35:16+00:00 ERR (3): 
exception 'DataNotLoadedException' with message 'Implementation Error: the data is not up to date. Please use 'FACTFinder_Http_ParallelDataProvider::loadAllData' before trying to get data!' in /PATH/TO/MAGENTO/web/lib/FACTFinder/Http/ParallelDataProvider.php:197
Stack trace:
#0 /PATH/TO/MAGENTO/web/lib/FACTFinder/Http/ParallelDataProvider.php(248): FACTFinder_Http_ParallelDataProvider->getData('proxy1')
#1 /PATH/TO/MAGENTO/web/lib/FACTFinder/Abstract/Adapter.php(65): FACTFinder_Http_DataProviderProxy->getData()
#2 /PATH/TO/MAGENTO/web/lib/FACTFinder/Http/ScicAdapter.php(38): FACTFinder_Abstract_Adapter->getData()
#3 /PATH/TO/MAGENTO/web/app/code/community/Flagbit/FactFinder/Model/Facade.php(467): FACTFinder_Http_ScicAdapter->applyTracking()
#4 /PATH/TO/MAGENTO/web/app/code/community/Flagbit/FactFinder/Model/Facade.php(389): Flagbit_FactFinder_Model_Facade->_getFactFinderObject('scic', 'applyTracking', NULL, NULL)
#5 /PATH/TO/MAGENTO/web/app/code/community/Flagbit/FactFinder/Model/Handler/Tracking.php(55): Flagbit_FactFinder_Model_Facade->applyScicTracking()
#6 /PATH/TO/MAGENTO/web/app/code/community/Flagbit/FactFinder/Model/Observer.php(67): Flagbit_FactFinder_Model_Handler_Tracking->applyTracking()
#7 /PATH/TO/MAGENTO/web/app/code/core/Mage/Core/Model/App.php(1338): Flagbit_FactFinder_Model_Observer->addToCartSendSCIC(Object(Varien_Event_Observer))
#8 /PATH/TO/MAGENTO/web/app/code/core/Mage/Core/Model/App.php(1317): Mage_Core_Model_App->_callObserverMethod(Object(Flagbit_FactFinder_Model_Observer), 'addToCartSendSC...', Object(Varien_Event_Observer))
#9 /PATH/TO/MAGENTO/web/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('checkout_cart_p...', Array)
#10 /PATH/TO/MAGENTO/web/app/code/core/Mage/Checkout/Model/Cart.php(290): Mage::dispatchEvent('checkout_cart_p...', Array)
#11 /PATH/TO/MAGENTO/web/app/code/local/IronShark/Checkout/controllers/CartController.php(83): Mage_Checkout_Model_Cart->addProduct(Object(IronShark_Catalog_Model_Catalog_Product), Array)
#12 /PATH/TO/MAGENTO/web/app/code/core/Mage/Core/Controller/Varien/Action.php(418): IronShark_Checkout_CartController->addAction()
#13 /PATH/TO/MAGENTO/web/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('add')
#14 /PATH/TO/MAGENTO/web/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#15 /PATH/TO/MAGENTO/web/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#16 /PATH/TO/MAGENTO/web/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#17 /PATH/TO/MAGENTO/web/index.php(105): Mage::run('', 'store')
#18 {main}
```

**Number two**
```
2014-12-14T05:38:01+00:00 ERR (3): 
exception 'DataNotLoadedException' with message 'Implementation Error: the data is not up to date. Please use 'FACTFinder_Http_ParallelDataProvider::loadAllData' before trying to get data!' in /PATH/TO/MAGENTO/web/lib/FACTFinder/Http/ParallelDataProvider.php:197
Stack trace:
#0 /PATH/TO/MAGENTO/web/lib/FACTFinder/Http/ParallelDataProvider.php(248): FACTFinder_Http_ParallelDataProvider->getData('proxy1')
#1 /PATH/TO/MAGENTO/web/lib/FACTFinder/Abstract/Adapter.php(65): FACTFinder_Http_DataProviderProxy->getData()
#2 /PATH/TO/MAGENTO/web/lib/FACTFinder/Http/ScicAdapter.php(38): FACTFinder_Abstract_Adapter->getData()
#3 /PATH/TO/MAGENTO/web/app/code/community/Flagbit/FactFinder/Model/Facade.php(467): FACTFinder_Http_ScicAdapter->applyTracking()
#4 /PATH/TO/MAGENTO/web/app/code/community/Flagbit/FactFinder/Model/Facade.php(389): Flagbit_FactFinder_Model_Facade->_getFactFinderObject('scic', 'applyTracking', NULL, NULL)
#5 /PATH/TO/MAGENTO/web/app/code/community/Flagbit/FactFinder/Model/Handler/Tracking.php(55): Flagbit_FactFinder_Model_Facade->applyScicTracking()
#6 /PATH/TO/MAGENTO/web/app/code/community/Flagbit/FactFinder/Model/Observer.php(196): Flagbit_FactFinder_Model_Handler_Tracking->applyTracking()
#7 [internal function]: Flagbit_FactFinder_Model_Observer->processScicOrderQueue(Object(Aoe_Scheduler_Model_Schedule))
#8 /PATH/TO/MAGENTO/web/app/code/community/Aoe/Scheduler/Model/Observer.php(79): call_user_func_array(Array, Array)
#9 /PATH/TO/MAGENTO/web/app/code/core/Mage/Core/Model/App.php(1338): Aoe_Scheduler_Model_Observer->dispatch(Object(Varien_Event_Observer))
#10 /PATH/TO/MAGENTO/web/app/code/core/Mage/Core/Model/App.php(1317): Mage_Core_Model_App->_callObserverMethod(Object(Aoe_Scheduler_Model_Observer), 'dispatch', Object(Varien_Event_Observer))
#11 /PATH/TO/MAGENTO/web/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('default', Array)
#12 /PATH/TO/MAGENTO/web/cron.php(76): Mage::dispatchEvent('default')
#13 {main}
```

These errors were already reported in the issue: 

https://github.com/Flagbit/Magento-FACTFinder/issues/63

and fixed in this commit:

https://github.com/Flagbit/Magento-FACTFinder/commit/f6667a8fd2b28af6f40a7dc940648ba122b99986 .

But exactly this fix is already in our code and the errors will be still logged.

Our Environment:
* Magento Extension Flagbit FactFinder
* Version 3.5.4
* Magento Version 1.8.1 & 1.9.1 (CE)

**Comment by rudibatt** [comment]
This is a problem at the tracking implementation. I fixed it at https://github.com/Flagbit/Magento-FACTFinder/commit/d6e57974564967e1d42dc40532062074951c5595, but this was part of a rewrite of the whole tracking integration, so I am not sure any more, if this fix will work.

**Comment by rudibatt** [comment]
btw, the whole rewrite was merged at this commit: https://github.com/Flagbit/Magento-FACTFinder/commit/d6d2ce78c318e0dd8ed6110e504230ae8929da6e

**Comment by Sidt** [comment]
Thank you for the fast reply, I will try https://github.com/Flagbit/Magento-FACTFinder/commit/d6e57974564967e1d42dc40532062074951c5595
